/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package device.code.sql.server.driver;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
